services:
  mysql:
    image: mysql
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: Test@123
      MYSQL_DATABASE: bankapp
    healthcheck:
      test: ["CMD", "mysqladmin","ping","-h","localhost","-u","root","-pTest@123"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
    volumes:
      - bankapp-vol:/var/lib/mysql
    networks:
      - bankapp-nw
  
  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    networks:
      - bankapp-nw
    volumes:
      - ollama:/root/.ollama
    command: "serve"
    healthcheck:
      test: ["CMD","ollama","list"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s

  ollama-model:
    image: ollama/ollama
    container_name: ollama-model
    environment:
      OLLAMA_HOST: ollama
      OLLAMA_URL: http://ollama:11434
    entrypoint: /bin/sh
    command: -c "ollama pull tinyllama"
    networks:
      - bankapp-nw
    volumes:
      - ollama:/root/.ollama
    depends_on:
      ollama:
        condition: service_healthy


    



  bankapp:
    build: .
    container_name: bankapp
    ports:
      - "8080:8080"
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: Test@123
      MYSQL_PORT: 3306
      MYSQL_DATABASE: bankappdb
      OLLAMA_URL: http://ollama:11434
    depends_on:
      mysql:
        condition: service_healthy
      ollama-model:
        condition: service_completed_successfully
    networks:
      - bankapp-nw

volumes:
  ollama:
  bankapp-vol:
    external: true

networks:
  bankapp-nw:
    external: true
