apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: bankapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:latest
          ports:
            - containerPort: 3306
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu:  "500m"
          volumeMounts:
            - mountPath: "var/lib/mysql"
              name: mysql-vol
          env:
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: config
                  key: MYSQL_DATABASE

            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: MYSQL_PASSWORD
      volumes:
        - name: mysql-vol
          persistentVolumeClaim:
            claimName: mysql-claim     