apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-claim
  namespace: bankapp
spec:
  selector:
     matchLabels:
       app: mysql-vol
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  resources:
    requests:
      storage: 5Gi

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ollama-claim
  namespace: bankapp
spec:
  selector:
    matchLabels: 
      app: ollama-vol
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  resources:
    requests:
      storage: 5Gi
